- name: Loop
  hosts: localhost
  tasks:
    - name: Print fruit name
      ansible.builtin.debug:
        msg: Fruit name - Apple

    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruit name - {{ item }}                          #item is default variable
      loop:                                                 #loop is keyword
        - apple
        - banana
        - goa

    - name: Print Fruit Name with quantity
      ansible.builtin.debug:
        msg: Fruit name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - { name: fruit1, quantity: 10,}
        - { name: fruit2, quantity: 20,}
        - { name: fruit3, quantity: 30,}